package com.arokia.accounts.service.impl;

import com.arokia.accounts.constants.AccountsConstants;
import com.arokia.accounts.dto.AccountsDto;
import com.arokia.accounts.dto.CustomerDto;
import com.arokia.accounts.entity.Accounts;
import com.arokia.accounts.entity.Customer;
import com.arokia.accounts.exception.CustomerAlreadyExistsException;
import com.arokia.accounts.exception.ResourceNotFoundException;
import com.arokia.accounts.mapper.AccountsMapper;
import com.arokia.accounts.mapper.CustomerMapper;
import com.arokia.accounts.repositories.AccountsRepository;
import com.arokia.accounts.repositories.CustomerRepository;
import com.arokia.accounts.service.IAccountsService;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.Random;

@Service
@AllArgsConstructor
public class AccountsServiceImpl implements IAccountsService {

    /*
       By using @AllArgsConstructor, Lombok will create constructor to accept all argument of this class.
       Whenever we have only single constructor inside our class accepting parameter, we dont need to
       manually autowire below repo using @Autowire.
       Spring framework can automatically do the autowiring as class contains only one constructor,
       which accepts all parameter
     */
    private AccountsRepository accountsRepository;
    private CustomerRepository customerRepository;

    /**
     * @param customerDto - CustomerDto Object
     */
    @Override
    public void createAccount(CustomerDto customerDto) {
        /*
            InOrder to save the data into database using repository Interface, we need to send the
            Object of Customer but not the class. Hence there should be some mapping logic which will convert
            DTO to entity class & entity to DTO. So Create CustomerMapper, AccountsMapper.
         */
        Customer customer = CustomerMapper.mapToCustomer(customerDto, new Customer());
        //Handling exception to avoid duplicate customer. So create CustomerAlreadyExistsException
        Optional<Customer> optionalCustomer = customerRepository.findByMobileNumber(customerDto.getMobileNumber());
        if(optionalCustomer.isPresent()) {
            throw new CustomerAlreadyExistsException("Customer already registered with given mobileNumber "
                    +customerDto.getMobileNumber());
        }

        //Later we can do how to automatically handle below code using Spring Data JPA
        customer.setCreatedAt(LocalDateTime.now());
        customer.setCreatedBy("Peter");

        Customer savedCustomer = customerRepository.save(customer);
        //We need to know the customer ID generated by .save method, so return the saved object to savedCustomer
        //and pass it to account repository to save in accounts table.
        accountsRepository.save(createNewAccount(savedCustomer));
    }


    /**
     * @param customer - Customer Object
     * @return the new account details
     */
    private Accounts createNewAccount(Customer customer) {
        Accounts newAccount = new Accounts();
        newAccount.setCustomerId(customer.getCustomerId());
        long randomAccNumber = 1000000000L + new Random().nextInt(900000000);
        //Above will return 10 digit account number

        newAccount.setAccountNumber(randomAccNumber);
        newAccount.setAccountType(AccountsConstants.SAVINGS);
        newAccount.setBranchAddress(AccountsConstants.ADDRESS);

        /*newAccount.setCreatedAt(LocalDateTime.now());
        newAccount.setCreatedBy("Peter");
        Achieved by @EntityListeners(AuditingEntityListener.class) in BaseEntity class*/
        return newAccount;
    }

    /**
     * @param mobileNumber - Input Mobile Number
     * @return Accounts Details based on a given mobileNumber
     */
    @Override
    public CustomerDto fetchAccount(String mobileNumber) {
        Customer customer = customerRepository.findByMobileNumber(mobileNumber).orElseThrow(
                () -> new ResourceNotFoundException("Customer", "mobileNumber", mobileNumber)
        );
        Accounts accounts = accountsRepository.findByCustomerId(customer.getCustomerId()).orElseThrow(
                () -> new ResourceNotFoundException("Account", "customerId", customer.getCustomerId().toString())
        );
        CustomerDto customerDto = CustomerMapper.mapToCustomerDto(customer, new CustomerDto());
        customerDto.setAccountsDto(AccountsMapper.mapToAccountsDto(accounts, new AccountsDto()));
        return customerDto;
    }

    /**
     * @param customerDto - CustomerDto Object
     * @return boolean indicating if the update of Account details is successful or not
     */
    @Override
    public boolean updateAccount(CustomerDto customerDto) {
        boolean isUpdated = false;
        AccountsDto accountsDto = customerDto.getAccountsDto();
        if(accountsDto !=null ){
            Accounts accounts = accountsRepository.findById(accountsDto.getAccountNumber()).orElseThrow(
                    () -> new ResourceNotFoundException("Account", "AccountNumber", accountsDto.getAccountNumber().toString())
            );
            AccountsMapper.mapToAccounts(accountsDto, accounts);
            accounts = accountsRepository.save(accounts);

            Long customerId = accounts.getCustomerId();
            Customer customer = customerRepository.findById(customerId).orElseThrow(
                    () -> new ResourceNotFoundException("Customer", "CustomerID", customerId.toString())
            );
            CustomerMapper.mapToCustomer(customerDto,customer);
            customerRepository.save(customer);
            isUpdated = true;
        }
        return  isUpdated;
    }

    /**
     * @param mobileNumber - Input Mobile Number
     * @return boolean indicating if the delete of Account details is successful or not
     */
    @Override
    public boolean deleteAccount(String mobileNumber) {
        Customer customer = customerRepository.findByMobileNumber(mobileNumber).orElseThrow(
                () -> new ResourceNotFoundException("Customer", "mobileNumber", mobileNumber)
        );
        accountsRepository.deleteByCustomerId(customer.getCustomerId());
        customerRepository.deleteById(customer.getCustomerId());
        return true;
    }

}
